const mongoose = require('mongoose')

var Form1 = mongoose.Schema({
    clickedForm1: Boolean,
    userId: String,
    advNo: String,
    transactionId: String,
    bankName: String,
    branchName: String,
    ifsc: String,
    amount: Number,
    date: String,
    name: String,
    motherName: String,
    fatherName: String,
    houseNoResidential: String,
    landmarkResidential: String,
    streetResidential: String,
    streetResidential1: String,
    cityResidential: String,
    districtResidential: String,
    postResidential :String,
    policeResidential: String,
    stateResidential: String,
    countryResidential: String,
    pincodeResidential: Number,
    houseNoPermanent: String,
    streetPermanent: String,
    streetPermanent1: String,
    landmarkPermanent: String,
    cityPermanent: String,
    districtPermanent: String,
    postPermanent :String,
    policePermanent: String,
    statePermanent: String,
    countryPermanent: String,
    pincodePermanent: Number,
    email: String,
    mobileNo: Number,
    mobileNo1: Number,
    gender: String,
    DOB: Date,
    age: Number,
    maritalStatus: String,
    category: String,
    pwd: Boolean,
    disability: String
})

var Form1 = module.exports = mongoose.model('Form1',Form1)